export const dataTest = [
  [
    {
      title: "Bitter & Vermut",
      listItem: ["Campari", "Martini", "Aperol"],
      listGramm: ["1/40", "1/40", "1/40"],
      listPrice: [57, 57, 57],
    },
    {
      title: "Aperitive & Degestive",
      listItem: ["Beherovca", "Jagermeister"],
      listGramm: ["1/40", "1/40"],
      listPrice: [57, 57],
    },
    {
      title: "Champagne & Sparkling Wine",
      listItem: [
        "Cricova Cuvee Prestige",
        "Asti Martini",
        "Asti Martini Prosecco",
        "Foss Marai Prosseco",
        "Moet & Chandon",
      ],
      listGramm: ["1/750", "1/750", "1/750", "1/750", "1/750"],
      listPrice: [380, 475, 475, 570, 2850],
    },
    {
      title: "Wine Moldova",
      listItem: [
        "Timbrus Chardonnay",
        "Timbrus Polifonia",
        "Timbrus Barrel Fermented",
        "Timbrus De Autor Blend №3",
        "Alb de Purcari",
        "Negru de Purcari",
      ],
      listGramm: ["1/150", "1/150", "1/750", "1/750", "1/750", "1/750"],
      listPrice: [57, 57, 570, 570, 950, 950],
    },
    {
      title: "Wine Italy",
      listItem: ["Piccini Pinot", "Piccini Chianti"],
      listGramm: ["1/150", "1/150"],
      listPrice: [57, 57],
    },
    {
      title: "Wine Georgia",
      listItem: ["Khvachkara", "Mukuzani", "Tsinandali"],
      listGramm: ["1/750", "1/750", "1/750"],
      listPrice: [570, 475, 475],
    },
    {
      title: "Vodka",
      listItem: ["Absolut", "Finlandia", "Grey Goose"],
      listGramm: ["1/40", "1/40", "1/40"],
      listPrice: [57, 57, 190],
    },
    {
      title: "Tequila",
      listItem: ["Sauza", "Volcan"],
      listGramm: ["1/40", "1/40"],
      listPrice: [95, 285],
    },
    {
      title: "Gin",
      listItem: ["Beefeater", "Gordons"],
      listGramm: ["1/40", "1/40"],
      listPrice: [95, 95],
    },
    {
      title: "Brandy & Cognac",
      listItem: [
        "Surpriznii 10 YO",
        "Kvint XO 14 YO",
        "Hennessy VSOP",
        "Hennessy XO",
      ],
      listGramm: ["1/40", "1/40", "1/40", "1/40"],
      listPrice: [95, 285, 380, 760],
    },
  ],
  [
    {
      title: "Rum",
      listItem: ["Bacardi"],
      listGramm: ["1/40"],
      listPrice: [95],
    },
    {
      title: "Whisky",
      listItem: [
        "Glenmorange",
        "J W Red Label",
        "J W Black Label",
        "Jameson",
        "Jack Daniels",
        "Chivas Regal 12 YO",
        "Macallan 12 YO",
      ],
      listGramm: ["1/40", "1/40", "1/40", "1/40", "1/40", "1/40", "1/40"],
      listPrice: [285, 95, 190, 95, 95, 190, 380],
    },
    {
      title: "Liqueur",
      listItem: ["Kahlua", "Baileys", "Sambuca"],
      listGramm: ["1/40", "1/40", "1/40"],
      listPrice: [57, 57, 57],
    },
    {
      title: "Energy Drinks",
      listItem: ["Tiger", "Red Bull"],
      listGramm: [1, 1],
      listPrice: [57, 95],
    },
    {
      title: "Soft Drinks",
      listItem: [
        "Cola, Fanta, Sprite",
        "Evian",
        "Bucovina",
        "Norda",
        "Borjomi",
        "Fresh Juices",
        "Lemonade",
      ],
      listGramm: [
        "1/250",
        "1/330",
        "1/500",
        "1/500",
        "1/500",
        "1/180",
        "1/270",
      ],
      listPrice: [95, 95, 57, 57, 95, 95, 57],
    },
    {
      title: "Coffe",
      listItem: ["Espresso", "Cappucino", "Latte"],
      listGramm: [1, 1, 1],
      listPrice: [30, 30, 40],
    },
    {
      title: "Tea",
      listItem: ["Assorted tea", "Ronnefeldt"],
      listGramm: [1, 1],
      listPrice: [10, 40],
    },
    {
      title: "Snacks",
      listItem: ["Nuts", "Pistachios", "Ciocolata Bucuria"],
      listGramm: ["1/50", "1/25", 1],
      listPrice: [70, 35, 40],
    },
    {
      title: "Beer",
      listItem: [
        "Heineken",
        "Krombacher",
        "Krombacher Zero",
        "Biera Moretti Zero",
      ],
      listGramm: ["1/330", "1/330", "1/330", "1/330"],
      listPrice: [95, 95, 95, 95],
    },
  ],
  [
    {
      title: "Breakfas",
      listItem: [
        "Omlette",
        "Oatmeal with fresh fruits",
        "Pancakes with red caviar",
        "Pancakes with salmon",
        "Bread and butter with caviar",
        "Bread and butter with salmon",
        "Turkish breakfast",
        "NUOVO breakfast",
      ],
      listGramm: [
        "1/180",
        "1/200/30",
        "1/180/30",
        "1/180/80",
        "1/20/10/15",
        "1/20/15/25",
        "1/325",
        "1/325",
      ],
      listPrice: [40, 30, 180, 120, 90, 70, 125, 75],
    },
    {
      title: "Salds & Appetixers",
      listItem: [
        "Cesar salad with shrimps",
        "Cesar salad with chicken",
        "Salamon carpaccio",
        "Veal carpaccio",
        "Greel salad",
        "Eggplant caviar",
      ],
      listGramm: ["1/310", "1/290", "1/100", "1/100", "1/265", "1/180"],
      listPrice: [150, 90, 180, 120, 90, 70],
    },
    {
      title: "Soups",
      listItem: ["Zama", "Mushroom cream soup"],
      listGramm: ["1/300", "1/300"],
      listPrice: [50, 60],
    },
    {
      title: "Second Courses",
      listItem: [
        "Grilled salmon steak",
        "Grilled Dorada",
        "Shrimps with Salsa",
        "Grilled tiger prawns",
        "Chiccken steak",
        "Chick Tabaka",
        "Ribeye steak",
        "Rack of milk veal",
        "Spaghetti Bolognese",
        "Burger",
        "Club sandwich with french fries",
      ],
      listGramm: [
        "1/200/70",
        "1/350/70",
        "1/230",
        "1/250",
        "1/170/30",
        "1/500",
        "1/300/30",
        "1/270/80",
        "1/300",
        "1/220/150/30",
        "1/160/100",
      ],
      listPrice: [300, 280, 175, 275, 120, 220, 800, 300, 110, 190, 130],
    },
    {
      title: "Side Dishes",
      listItem: [
        "Rice with vegetables",
        "French fries",
        "Mashed potatoes",
        "Grilled vegetables",
      ],
      listGramm: ["1/150", "1/220", "1/150", "1/250"],
      listPrice: [30, 40, 30, 50],
    },
    {
      title: "Desserts",
      listItem: [
        "Fruit platter",
        "Cheese platter",
        "Ice-Cream",
        "Tiramisu",
        "CheeseCake",
      ],
      listGramm: ["1/250", "1/270", "1/100", "1/120", "1/120"],
      listPrice: [100, 200, 25, 65, 65],
    },
  ],
];
