export const dataTest = [
  [
    {
      title: "Bitter & Vermut",
      listItem: ["Campari", "Martini", "Aperol"],
      listGramm: ["1/40", "1/40", "1/40"],
      listPrice: [90, 90, 90],
    },
    {
      title: "Aperitive & Degestive",
      listItem: ["Jagermeister"],
      listGramm: ["1/40"],
      listPrice: [90],
    },
    {
      title: "Champagne & Sparkling Wine",
      listItem: [
        "Cricova Cuvee Prestige",
        "Asti Martini",
        "Foss Marai Prosseco",
        "Moet & Chandon",
      ],
      listGramm: ["1/750", "1/750", "1/750", "1/750"],
      listPrice: [900, 810, 1080, 2880],
    },
    {
      title: "Wine Moldova",
      listItem: [
        "Timbrus Chardonnay",
        "Timbrus Polifonia",
        "Timbrus Barrel Fermented",
        "Timbrus De Autor Blend №3",
        "Alb de Purcari",
        "Negru de Purcari",
      ],
      listGramm: ["1/150", "1/150", "1/750", "1/750", "1/750", "1/750"],
      listPrice: [180, 180, 1080, 1080, 1260, 1260],
    },
    {
      title: "Wine Italy",
      listItem: ["Piccini Pinot", "Piccini Chianti"],
      listGramm: ["1/150", "1/150"],
      listPrice: [180, 180],
    },
    {
      title: "Wine Georgia",
      listItem: ["Mukuzani"],
      listGramm: ["1/750"],
      listPrice: [810],
    },
    {
      title: "Vodka",
      listItem: ["Absolut", "Finlandia", "Grey Goose"],
      listGramm: ["1/40", "1/40", "1/40"],
      listPrice: [90, 90, 270],
    },
    {
      title: "Tequila",
      listItem: ["Sauza", "Volcan"],
      listGramm: ["1/40", "1/40"],
      listPrice: [95, 285],
    },
    {
      title: "Gin",
      listItem: ["Beefeater", "Gordons"],
      listGramm: ["1/40", "1/40"],
      listPrice: [90, 90],
    },
    {
      title: "Brandy & Cognac",
      listItem: ["Surpriznii 10 YO", "Hennessy VSOP", "Hennessy XO"],
      listGramm: ["1/40", "1/40", "1/40"],
      listPrice: [180, 450, 1260],
    },
  ],
  [
    {
      title: "Rum",
      listItem: ["Bacardi"],
      listGramm: ["1/40"],
      listPrice: [90],
    },
    {
      title: "Whisky",
      listItem: [
        "Glenmorange",
        "J W Red Label",
        "J W Black Label",
        "Jameson",
        "Jack Daniels",
        "Chivas Regal 12 YO",
        "Macallan 12 YO",
      ],
      listGramm: ["1/40", "1/40", "1/40", "1/40", "1/40", "1/40", "1/40"],
      listPrice: [360, 90, 180, 90, 90, 270, 540],
    },
    {
      title: "Liqueur",
      listItem: ["Kahlua", "Baileys", "Sambuca"],
      listGramm: ["1/40", "1/40", "1/40"],
      listPrice: [90, 90, 90],
    },
    {
      title: "Energy Drinks",
      listItem: ["Tiger", "Red Bull"],
      listGramm: [1, 1],
      listPrice: [90, 90],
    },
    {
      title: "Soft Drinks",
      listItem: [
        "Cola, Fanta, Sprite",
        "Evian",
        "Bucovina",
        "Norda",
        "Borjomi",
        "Fresh Juices",
        "Lemonade",
      ],
      listGramm: [
        "1/250",
        "1/330",
        "1/500",
        "1/500",
        "1/500",
        "1/180",
        "1/270",
      ],
      listPrice: [90, 90, 90, 90, 90, 90, 90],
    },
    {
      title: "Coffe",
      listItem: ["Espresso", "Cappucino", "Latte"],
      listGramm: [1, 1, 1],
      listPrice: [36, 74, 74],
    },
    {
      title: "Tea",
      listItem: ["Assorted tea", "Ronnefeldt"],
      listGramm: [1, 1],
      listPrice: [18, 74],
    },
    {
      title: "Snacks",
      listItem: ["Nuts", "Pistachios", "Ciocolata Bucuria"],
      listGramm: ["1/50", "1/25", 1],
      listPrice: [90, 90, 90],
    },
    {
      title: "Beer",
      listItem: [
        "Heineken",
        "Krombacher",
        "Krombacher Zero",
        "Biera Moretti Zero",
      ],
      listGramm: ["1/330", "1/330", "1/330", "1/330"],
      listPrice: [90, 90, 90, 90],
    },
  ],
  [
    {
      title: "Breakfas",
      listItem: [
        "Omlette",
        "Oatmeal with fresh fruits",
        "Pancakes with red caviar",
        "Pancakes with salmon",
        "Bread and butter with caviar",
        "Bread and butter with salmon",
      ],
      listGramm: [
        "1/180",
        "1/200/30",
        "1/180/30",
        "1/180/80",
        "1/20/10/15",
        "1/20/15/25",
      ],
      listPrice: [90, 54, 270, 180, 180, 90],
    },
    {
      title: "Salds & Appetixers",
      listItem: [
        "Cesar salad with shrimps",
        "Cesar salad with chicken",
        "Salamon carpaccio",
        "Veal carpaccio",
        "Greel salad",
      ],
      listGramm: ["1/310", "1/290", "1/100", "1/100", "1/265"],
      listPrice: [270, 180, 270, 270, 90],
    },
    {
      title: "Soups",
      listItem: ["Zama"],
      listGramm: ["1/300"],
      listPrice: [90],
    },
    {
      title: "Second Courses",
      listItem: [
        "Grilled salmon steak",
        "Grilled Dorada",
        "Shrimps with Salsa",
        "Grilled tiger prawns",
        "Chiccken steak",
        "Chick Tabaka",
        "Ribeye steak",
        "Rack of milk veal",
        "Spaghetti Bolognese",
        "Burger",
        "Club sandwich with french fries",
      ],
      listGramm: [
        "1/200/70",
        "1/350/70",
        "1/230",
        "1/250",
        "1/170/30",
        "1/500",
        "1/300/30",
        "1/270/80",
        "1/300",
        "1/220/150/30",
        "1/160/100",
      ],
      listPrice: [450, 540, 270, 360, 180, 270, 1800, 720, 180, 360, 180],
    },
    {
      title: "Side Dishes",
      listItem: ["French fries", "Grilled vegetables"],
      listGramm: ["1/220", "1/250"],
      listPrice: [90, 90],
    },
    {
      title: "Desserts",
      listItem: ["Fruit platter", "Cheese platter", "Ice-Cream"],
      listGramm: ["1/250", "1/270", "1/100"],
      listPrice: [180, 200, 90],
    },
  ],
];
